# Generated by Django 3.2.5 on 2022-12-31 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20221231_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='gifUrl',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Gif URL'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 12, 31, 10, 24, 16, 199014, tzinfo=utc)),
        ),
    ]
