# Generated by Django 3.2.5 on 2022-12-31 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20221231_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 12, 31, 10, 43, 57, 539145, tzinfo=utc)),
        ),
    ]
