# Generated by Django 3.2.5 on 2023-01-02 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_training_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise_done',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exercise_done',
            name='sets',
        ),
        migrations.AlterField(
            model_name='exercise_done',
            name='exercise',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 2, 11, 4, 0, 428291, tzinfo=utc)),
        ),
    ]
