# Generated by Django 3.2.5 on 2023-01-02 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20230102_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingexercise',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Weight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 2, 12, 5, 45, 596948, tzinfo=utc)),
        ),
    ]
