# Generated by Django 3.2.5 on 2023-01-02 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20230102_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingexercise',
            name='unit',
            field=models.CharField(choices=[('pounds', 'pounds'), ('kilogram', 'kilogram')], default='kilogram', max_length=10),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 2, 12, 17, 42, 121329, tzinfo=utc)),
        ),
    ]
