# Generated by Django 3.2.5 on 2023-01-02 18:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20230102_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 2, 16, 46, 28, 191644, tzinfo=utc)),
        ),
    ]
