# Generated by Django 4.1 on 2023-01-04 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_alter_training_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="training",
            name="end_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 1, 4, 18, 19, 31, 732610)
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="start_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 1, 4, 16, 49, 31, 732610)
            ),
        ),
    ]
