# Generated by Django 4.1 on 2023-01-04 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_training_description_alter_training_end_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="training", old_name="description", new_name="describtion",
        ),
        migrations.AlterField(
            model_name="training",
            name="end_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 1, 4, 18, 22, 17, 72869)
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="start_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 1, 4, 16, 52, 17, 72869)
            ),
        ),
    ]
