# Generated by Django 3.2.5 on 2023-01-05 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_rename_description_training_describtion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='describtion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='training',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 5, 16, 20, 19, 364159)),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 5, 14, 50, 19, 364142)),
        ),
    ]
