# Generated by Django 3.2.5 on 2023-01-05 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20230105_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='date_created',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 5, 22, 1, 10, 283087)),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 5, 20, 31, 10, 283069)),
        ),
    ]
