# Generated by Django 4.1 on 2023-01-06 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0029_auto_20230105_2201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="end_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 1, 6, 11, 5, 39, 765084)
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="start_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 1, 6, 9, 35, 39, 765084)
            ),
        ),
    ]
