# Generated by Django 4.1.5 on 2023-01-06 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_alter_training_end_time_alter_training_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='show_to',
            field=models.CharField(blank=True, choices=[('everyone', 2), ('friends', 1), ('only me', 0)], default=1, max_length=10, null=True, verbose_name='Who can view this training:'),
        ),
        migrations.AlterField(
            model_name='training',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 6, 16, 52, 15, 391784)),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 6, 15, 22, 15, 391770)),
        ),
    ]
