# Generated by Django 4.1.5 on 2023-01-06 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_alter_training_end_time_alter_training_show_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 6, 17, 0, 15, 515878)),
        ),
        migrations.AlterField(
            model_name='training',
            name='show_to',
            field=models.CharField(choices=[(2, 'everyone'), (1, 'my followers'), (0, 'only me')], default=1, max_length=10, null=True, verbose_name='Who can view this training:'),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 6, 15, 30, 15, 515863)),
        ),
    ]
