# Generated by Django 4.1.5 on 2023-01-06 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_alter_training_end_time_alter_training_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 6, 19, 31, 9, 729349)),
        ),
        migrations.AlterField(
            model_name='training',
            name='show_to',
            field=models.CharField(choices=[('2', 'everyone'), ('1', 'my followers'), ('0', 'only me')], default=1, max_length=10, null=True, verbose_name='Who can view this training:'),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 6, 18, 1, 9, 729335)),
        ),
    ]
