# Generated by Django 4.1.5 on 2023-01-06 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_alter_training_end_time_alter_training_show_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='end_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
