# Generated by Django 4.1.5 on 2023-01-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_comment_updated_at_alter_training_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
