# Generated by Django 4.1.5 on 2023-01-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(related_name='followers', to='members.userprofile'),
        ),
    ]
